---
- name: Docker build and push
  hosts: local  # Replace with the hostname or IP address of your target server
  become: yes  # Run tasks with sudo privileges

  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes   

    - name: Tag Docker image
      command: docker tag petstore rizwanshaukat/petstore:latest 

    - name: Log in to Docker Hub
      community.docker.docker_login:
        username: "{{ lookup('env', 'DOCKER_USERNAME') }}"
        password: "{{ lookup('env', 'DOCKER_PASSWORD') }}"

    - name: Push Docker image
      community.docker.docker_image_push:
      command: sudo docker push rizwanshaukat/petstore:latest

    - name: Run Docker container
      command: docker run -d --name pet1 -p 8081:8080 rizwanshaukat/petstore:latest
