---
- name: Deploy Kubernetes Application
  hosts: k8s  # Replace with your target Kubernetes master host or group
  gather_facts: yes  # Gather facts about the target host

  tasks:
    - name: Copy deployment.yaml to Kubernetes master
      copy:
        src: /var/lib/jenkins/workspace/petstore/deployment.yaml  # Assuming Jenkins workspace variable
        dest: /home/ubuntu/
      become: yes  # Use sudo for copying if required
      become_user: root  # Use a privileged user for copying if required

    - name: Check if deployment exists
      command: kubectl get deployment petshop -o name
      register: deployment_check
      ignore_errors: yes

    - name: Print message if deployment exists
      debug:
        msg: "Deployment 'petshop' exists."
      when: deployment_check.rc == 0

    - name: Delete existing deployment if it exists
      command: kubectl delete deployment petshop
      when: deployment_check.rc == 0
      ignore_errors: yes

    - name: Check if service exists
      command: kubectl get service petshop -o name
      register: service_check
      ignore_errors: yes

    - name: Print message if service exists
      debug:
        msg: "Service 'petshop' exists."
      when: service_check.rc == 0

    - name: Delete existing service if it exists
      command: kubectl delete service petshop
      when: service_check.rc == 0
      ignore_errors: yes

    - name: Apply Deployment
      command: kubectl apply -f /home/ubuntu/deployment.yaml

    - name: Remove deployment.yaml file after applying deployment
      command: rm -rf /home/ubuntu/deployment.yaml
      become: yes  # Use sudo if needed for permissions
      become_user: root  # Use a privileged user for file removal if required
