---
- name: Deploy Kubernetes Application
  hosts: k8s  # Replace with your target Kubernetes master host or group
  gather_facts: yes  # Gather facts about the target host

  tasks:
    - name: Remove existing deployment.yaml file
      command: rm -rf /home/ubuntu/deployment.yaml
      become: yes  # Use sudo if needed for permissions
      become_user: root

    - name: Copy deployment.yaml to Kubernetes master
      copy:
        src: /var/lib/jenkins/workspace/petstore/deployment.yaml  # Assuming Jenkins workspace variable
        dest: /home/ubuntu/
      become: yes  # Use sudo for copying if required
      become_user: root  # Use a privileged user for copying if required

    - name: Check Kubernetes Deployments
      block:
        - name: Get existing deployments
          command: kubectl get deployments -o name
          register: all_deployments
          ignore_errors: yes  # Ignore errors if no deployments are found
          failed_when: false
          changed_when: false
        - name: Deployments exists
          debug:
            msg: "Current deployments: {{ all_deployments.stdout_lines }}"
          when: all_deployments.rc == 0  # Only print if the command was successful
        - name: Delete existing deployment 'petshop' if it exists
          command: kubectl delete deployment petshop
          when: all_deployments.rc == 0
          ignore_errors: yes

    - name: Check Kubernetes Services
      block:
        - name: Get existing Services 
          command: kubectl get service -o name
          register: service_check
          ignore_errors: yes
        - name: Service exists
          debug:
            msg: "Current services: {{ service_check.stdout }}"
          when: service_check.rc == 0
        - name: Delete existing service 'petshop' if it exists
          command: kubectl delete service petshop
          when: service_check.rc == 0
          ignore_errors: yes

    - name: Apply the new deployment.yaml
      command: kubectl apply -f /home/ubuntu/deployment.yaml
