---
- name: Deploy Kubernetes Application
  hosts: k8s  # Replace with your target Kubernetes master host or group
  gather_facts: yes  # Gather facts about the target host

  tasks:
    - name: Copy deployment.yaml to Kubernetes master
      copy:
        src: /var/lib/jenkins/workspace/petstore/deployment.yaml  # Assuming Jenkins workspace variable
        dest: /home/ubuntu/
      become: yes  # Use sudo for copying if required
      become_user: root  # Use a privileged user for copying if required

    - name: Check if deployment exists using kubectl
      command: kubectl get deployment petshop -o name
      register: deployment_check
      ignore_errors: yes

    - name: Delete existing deployment if it exists
      command: kubectl delete deployment petshop
      when: deployment_check.rc == 0
      ignore_errors: yes

    - name: Check if service exists using kubectl
      command: kubectl get service petshop -o name
      register: service_check
      ignore_errors: yes

    - name: Delete existing service if it exists
      command: kubectl delete service petshop
      when: service_check.rc == 0
      ignore_errors: yes

    - name: Apply Deployment
      k8s:
        kubeconfig: /home/ubuntu/.kube/config  # Path to the kubeconfig if not on the master node
        state: present
        src: /home/ubuntu/deployment.yaml
